In [1]:
import torch
torch.__version__

'2.0.1'

### Creating Tensors

Quick run through with torch.Tensor class

#### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item

<function Tensor.item>

#### Vector

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [11]:
vector.size()

torch.Size([2])

#### Matrix

In [13]:
matrix = torch.tensor([[1,2],
                      [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [14]:
matrix.ndim

2

In [16]:
matrix.size()

torch.Size([2, 2])

#### Tensors

In [18]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

#### Random tensors

In [21]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0137, 0.4699, 0.2137, 0.2937],
         [0.5466, 0.9521, 0.8888, 0.8698],
         [0.0492, 0.0240, 0.3364, 0.0521]]),
 torch.float32)

In [22]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
torch.backends.mps.is_available()

True

In [24]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'